<a href="https://colab.research.google.com/github/NewTAs/EECuC/blob/main/EECuC_220110_Try1A.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import os
import re
import glob
import cv2
import numpy as np
from sklearn.model_selection import train_test_split

import tensorflow as tf

from google.colab import drive
drive.mount('CNNDATA')

Drive already mounted at CNNDATA; to attempt to forcibly remount, call drive.mount("CNNDATA", force_remount=True).


In [2]:
numberOfClass = 5
pictureWeightHeightSize = 224

train_datagen = tf.keras.preprocessing.image.ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow_from_directory(
        '/content/CNNDATA/MyDrive/CNNDATA/Train/',
        target_size=(pictureWeightHeightSize, pictureWeightHeightSize),
        batch_size=numberOfClass,
        class_mode='categorical')

test_datagen = tf.keras.preprocessing.image.ImageDataGenerator(rescale=1./255)

test_generator = test_datagen.flow_from_directory(
        '/content/CNNDATA/MyDrive/CNNDATA/Validation/',
        target_size=(pictureWeightHeightSize, pictureWeightHeightSize),    
        batch_size=numberOfClass,
        class_mode='categorical')

Found 300 images belonging to 5 classes.
Found 120 images belonging to 5 classes.


In [3]:
from tensorflow.keras.applications import ResNet50V2

model = ResNet50V2(include_top=True, weights=None, input_shape=(224, 224, 3), pooling=max, classes=5)

In [4]:
model.compile(loss='categorical_crossentropy', metrics=['accuracy'], optimizer='adam')
model.summary()

Model: "resnet50v2"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_1 (InputLayer)           [(None, 224, 224, 3  0           []                               
                                )]                                                                
                                                                                                  
 conv1_pad (ZeroPadding2D)      (None, 230, 230, 3)  0           ['input_1[0][0]']                
                                                                                                  
 conv1_conv (Conv2D)            (None, 112, 112, 64  9472        ['conv1_pad[0][0]']              
                                )                                                                 
                                                                                         

In [5]:
model.fit(train_generator, epochs=100, validation_data=test_generator)

Epoch 1/100
60/60 [==============================] - 52s 710ms/step - loss: 1.8245 - accuracy: 0.3600 - val_loss: 3.2546 - val_accuracy: 0.1000
Epoch 2/100
60/60 [==============================] - 12s 191ms/step - loss: 1.4469 - accuracy: 0.4500 - val_loss: 3.7851 - val_accuracy: 0.2500
Epoch 3/100
60/60 [==============================] - 11s 190ms/step - loss: 1.4487 - accuracy: 0.4533 - val_loss: 3.2727 - val_accuracy: 0.2000
Epoch 4/100
60/60 [==============================] - 11s 190ms/step - loss: 1.3245 - accuracy: 0.3933 - val_loss: 3.4399 - val_accuracy: 0.1000
Epoch 5/100
60/60 [==============================] - 11s 190ms/step - loss: 1.2738 - accuracy: 0.4967 - val_loss: 2.6567 - val_accuracy: 0.1667
Epoch 6/100
60/60 [==============================] - 11s 190ms/step - loss: 1.1428 - accuracy: 0.5400 - val_loss: 3.8297 - val_accuracy: 0.2417
Epoch 7/100
60/60 [==============================] - 11s 190ms/step - loss: 1.0388 - accuracy: 0.5933 - val_loss: 4.5647 - val_accuracy:

In [6]:
print("-- Evaluate --")
scores = model.evaluate(test_generator)
print("%s: %.2f%%" %(model.metrics_names[1], scores[1]*100))

-- Evaluate --
24/24 [==============================] - 1s 56ms/step - loss: 21.2180 - accuracy: 0.3833
accuracy: 38.33%


In [7]:
import matplotlib.pyplot as plt

In [8]:
val_datagen = tf.keras.preprocessing.image.ImageDataGenerator(rescale=1./255)

val_generator = val_datagen.flow_from_directory(
        '/content/CNNDATA/MyDrive/CNNDATA/Test/001/',
        target_size=(pictureWeightHeightSize, pictureWeightHeightSize),    
        batch_size=numberOfClass,
        class_mode='categorical')
print("-- Predict --")
output = model.predict(val_generator)
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
print(val_generator.filenames)
print(val_generator.class_indices)
print(output)

Found 1 images belonging to 1 classes.
-- Predict --
['0/015sub.png']
{'0': 0}
[[0.000 0.990 0.000 0.000 0.010]]


In [9]:
val_datagen = tf.keras.preprocessing.image.ImageDataGenerator(rescale=1./255)

val_generator = val_datagen.flow_from_directory(
        '/content/CNNDATA/MyDrive/CNNDATA/Test/002/',
        target_size=(pictureWeightHeightSize, pictureWeightHeightSize),    
        batch_size=numberOfClass,
        class_mode='categorical')
print("-- Predict --")
output = model.predict(val_generator)
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
print(val_generator.filenames)
print(val_generator.class_indices)
print(output)

Found 1 images belonging to 1 classes.
-- Predict --
['0/016sub.png']
{'0': 0}
[[0.000 1.000 0.000 0.000 0.000]]


In [10]:
val_datagen = tf.keras.preprocessing.image.ImageDataGenerator(rescale=1./255)

val_generator = val_datagen.flow_from_directory(
        '/content/CNNDATA/MyDrive/CNNDATA/Test/003/',
        target_size=(pictureWeightHeightSize, pictureWeightHeightSize),    
        batch_size=numberOfClass,
        class_mode='categorical')
print("-- Predict --")
output = model.predict(val_generator)
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
print(val_generator.filenames)
print(val_generator.class_indices)
print(output)

Found 1 images belonging to 1 classes.
-- Predict --
['0/031sub.png']
{'0': 0}
[[0.000 1.000 0.000 0.000 0.000]]


In [11]:
val_datagen = tf.keras.preprocessing.image.ImageDataGenerator(rescale=1./255)

val_generator = val_datagen.flow_from_directory(
        '/content/CNNDATA/MyDrive/CNNDATA/Test/004/',
        target_size=(pictureWeightHeightSize, pictureWeightHeightSize),    
        batch_size=numberOfClass,
        class_mode='categorical')
print("-- Predict --")
output = model.predict(val_generator)
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
print(val_generator.filenames)
print(val_generator.class_indices)
print(output)

Found 1 images belonging to 1 classes.
-- Predict --
['0/032sub.png']
{'0': 0}
[[0.000 1.000 0.000 0.000 0.000]]


In [12]:
val_datagen = tf.keras.preprocessing.image.ImageDataGenerator(rescale=1./255)

val_generator = val_datagen.flow_from_directory(
        '/content/CNNDATA/MyDrive/CNNDATA/Test/005/',
        target_size=(pictureWeightHeightSize, pictureWeightHeightSize),    
        batch_size=numberOfClass,
        class_mode='categorical')
print("-- Predict --")
output = model.predict(val_generator)
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
print(val_generator.filenames)
print(val_generator.class_indices)
print(output)

Found 1 images belonging to 1 classes.
-- Predict --
['0/047sub.png']
{'0': 0}
[[0.000 1.000 0.000 0.000 0.000]]


In [13]:
val_datagen = tf.keras.preprocessing.image.ImageDataGenerator(rescale=1./255)

val_generator = val_datagen.flow_from_directory(
        '/content/CNNDATA/MyDrive/CNNDATA/Test/006/',
        target_size=(pictureWeightHeightSize, pictureWeightHeightSize),    
        batch_size=numberOfClass,
        class_mode='categorical')
print("-- Predict --")
output = model.predict(val_generator)
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
print(val_generator.filenames)
print(val_generator.class_indices)
print(output)

Found 1 images belonging to 1 classes.
-- Predict --
['0/048sub.png']
{'0': 0}
[[0.000 1.000 0.000 0.000 0.000]]


In [14]:
val_datagen = tf.keras.preprocessing.image.ImageDataGenerator(rescale=1./255)

val_generator = val_datagen.flow_from_directory(
        '/content/CNNDATA/MyDrive/CNNDATA/Test/007/',
        target_size=(pictureWeightHeightSize, pictureWeightHeightSize),    
        batch_size=numberOfClass,
        class_mode='categorical')
print("-- Predict --")
output = model.predict(val_generator)
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
print(val_generator.filenames)
print(val_generator.class_indices)
print(output)

Found 1 images belonging to 1 classes.
-- Predict --
['0/063sub.png']
{'0': 0}
[[0.000 1.000 0.000 0.000 0.000]]


In [15]:
val_datagen = tf.keras.preprocessing.image.ImageDataGenerator(rescale=1./255)

val_generator = val_datagen.flow_from_directory(
        '/content/CNNDATA/MyDrive/CNNDATA/Test/008/',
        target_size=(pictureWeightHeightSize, pictureWeightHeightSize),    
        batch_size=numberOfClass,
        class_mode='categorical')
print("-- Predict --")
output = model.predict(val_generator)
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
print(val_generator.filenames)
print(val_generator.class_indices)
print(output)

Found 1 images belonging to 1 classes.
-- Predict --
['0/064sub.png']
{'0': 0}
[[0.000 0.068 0.000 0.000 0.932]]


In [16]:
val_datagen = tf.keras.preprocessing.image.ImageDataGenerator(rescale=1./255)

val_generator = val_datagen.flow_from_directory(
        '/content/CNNDATA/MyDrive/CNNDATA/Test/009/',
        target_size=(pictureWeightHeightSize, pictureWeightHeightSize),    
        batch_size=numberOfClass,
        class_mode='categorical')
print("-- Predict --")
output = model.predict(val_generator)
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
print(val_generator.filenames)
print(val_generator.class_indices)
print(output)

Found 1 images belonging to 1 classes.
-- Predict --
['0/079sub.png']
{'0': 0}
[[0.000 1.000 0.000 0.000 0.000]]


In [17]:
val_datagen = tf.keras.preprocessing.image.ImageDataGenerator(rescale=1./255)

val_generator = val_datagen.flow_from_directory(
        '/content/CNNDATA/MyDrive/CNNDATA/Test/010/',
        target_size=(pictureWeightHeightSize, pictureWeightHeightSize),    
        batch_size=numberOfClass,
        class_mode='categorical')
print("-- Predict --")
output = model.predict(val_generator)
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
print(val_generator.filenames)
print(val_generator.class_indices)
print(output)

Found 1 images belonging to 1 classes.
-- Predict --
['0/080sub.png']
{'0': 0}
[[0.000 1.000 0.000 0.000 0.000]]
