<a href="https://colab.research.google.com/github/NewTAs/EECuC/blob/main/EECuC_220112_Try2H.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import os
import re
import glob
import cv2
import numpy as np
from sklearn.model_selection import train_test_split

import tensorflow as tf

from google.colab import drive
drive.mount('CNNDATA')

Mounted at CNNDATA


In [2]:
numberOfClass = 5
pictureWeightHeightSize = 224

train_datagen = tf.keras.preprocessing.image.ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow_from_directory(
        '/content/CNNDATA/MyDrive/CNNDATA/Train/',
        target_size=(pictureWeightHeightSize, pictureWeightHeightSize),
        batch_size=numberOfClass,
        class_mode='categorical')

test_datagen = tf.keras.preprocessing.image.ImageDataGenerator(rescale=1./255)

test_generator = test_datagen.flow_from_directory(
        '/content/CNNDATA/MyDrive/CNNDATA/Validation/',
        target_size=(pictureWeightHeightSize, pictureWeightHeightSize),    
        batch_size=numberOfClass,
        class_mode='categorical')

Found 100 images belonging to 5 classes.
Found 40 images belonging to 5 classes.


In [3]:
from tensorflow.keras.applications import MobileNetV2

model = MobileNetV2(include_top=True, weights=None, input_shape=(224, 224, 3), pooling=max, classes=5)

In [4]:
model.compile(loss='categorical_crossentropy', metrics=['accuracy'], optimizer='adam')
model.summary()

Model: "mobilenetv2_1.00_224"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_1 (InputLayer)           [(None, 224, 224, 3  0           []                               
                                )]                                                                
                                                                                                  
 Conv1 (Conv2D)                 (None, 112, 112, 32  864         ['input_1[0][0]']                
                                )                                                                 
                                                                                                  
 bn_Conv1 (BatchNormalization)  (None, 112, 112, 32  128         ['Conv1[0][0]']                  
                                )                                              

In [5]:
model.fit(train_generator, epochs=100, validation_data=test_generator)

Epoch 1/100
20/20 [==============================] - 36s 1s/step - loss: 1.7673 - accuracy: 0.3200 - val_loss: 1.6097 - val_accuracy: 0.2000
Epoch 2/100
20/20 [==============================] - 2s 106ms/step - loss: 1.1346 - accuracy: 0.6000 - val_loss: 1.6111 - val_accuracy: 0.2000
Epoch 3/100
20/20 [==============================] - 2s 100ms/step - loss: 1.1379 - accuracy: 0.6400 - val_loss: 1.6172 - val_accuracy: 0.2000
Epoch 4/100
20/20 [==============================] - 2s 99ms/step - loss: 1.0371 - accuracy: 0.6500 - val_loss: 1.6254 - val_accuracy: 0.2000
Epoch 5/100
20/20 [==============================] - 2s 98ms/step - loss: 0.7022 - accuracy: 0.6800 - val_loss: 1.6611 - val_accuracy: 0.2000
Epoch 6/100
20/20 [==============================] - 2s 100ms/step - loss: 0.7266 - accuracy: 0.7700 - val_loss: 1.6730 - val_accuracy: 0.2000
Epoch 7/100
20/20 [==============================] - 2s 98ms/step - loss: 0.5759 - accuracy: 0.8300 - val_loss: 1.7305 - val_accuracy: 0.2000
Epoc

In [6]:
print("-- Evaluate --")
scores = model.evaluate(test_generator)
print("%s: %.2f%%" %(model.metrics_names[1], scores[1]*100))

-- Evaluate --
8/8 [==============================] - 0s 29ms/step - loss: 4.5855 - accuracy: 0.2000
accuracy: 20.00%


In [7]:
import matplotlib.pyplot as plt

In [8]:
val_datagen = tf.keras.preprocessing.image.ImageDataGenerator(rescale=1./255)

val_generator = val_datagen.flow_from_directory(
        '/content/CNNDATA/MyDrive/CNNDATA/Test/001/',
        target_size=(pictureWeightHeightSize, pictureWeightHeightSize),    
        batch_size=numberOfClass,
        class_mode='categorical')
print("-- Predict --")
output = model.predict(val_generator)
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
print(val_generator.filenames)
print(val_generator.class_indices)
print(output)

Found 1 images belonging to 1 classes.
-- Predict --
['0/015edge.png']
{'0': 0}
[[0.000 0.344 0.380 0.000 0.276]]


In [9]:
val_datagen = tf.keras.preprocessing.image.ImageDataGenerator(rescale=1./255)

val_generator = val_datagen.flow_from_directory(
        '/content/CNNDATA/MyDrive/CNNDATA/Test/002/',
        target_size=(pictureWeightHeightSize, pictureWeightHeightSize),    
        batch_size=numberOfClass,
        class_mode='categorical')
print("-- Predict --")
output = model.predict(val_generator)
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
print(val_generator.filenames)
print(val_generator.class_indices)
print(output)

Found 1 images belonging to 1 classes.
-- Predict --
['0/016edge.png']
{'0': 0}
[[0.000 0.344 0.380 0.000 0.276]]


In [10]:
val_datagen = tf.keras.preprocessing.image.ImageDataGenerator(rescale=1./255)

val_generator = val_datagen.flow_from_directory(
        '/content/CNNDATA/MyDrive/CNNDATA/Test/003/',
        target_size=(pictureWeightHeightSize, pictureWeightHeightSize),    
        batch_size=numberOfClass,
        class_mode='categorical')
print("-- Predict --")
output = model.predict(val_generator)
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
print(val_generator.filenames)
print(val_generator.class_indices)
print(output)

Found 1 images belonging to 1 classes.
-- Predict --
['0/031edge.png']
{'0': 0}
[[0.000 0.344 0.380 0.000 0.276]]


In [11]:
val_datagen = tf.keras.preprocessing.image.ImageDataGenerator(rescale=1./255)

val_generator = val_datagen.flow_from_directory(
        '/content/CNNDATA/MyDrive/CNNDATA/Test/004/',
        target_size=(pictureWeightHeightSize, pictureWeightHeightSize),    
        batch_size=numberOfClass,
        class_mode='categorical')
print("-- Predict --")
output = model.predict(val_generator)
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
print(val_generator.filenames)
print(val_generator.class_indices)
print(output)

Found 1 images belonging to 1 classes.
-- Predict --
['0/032edge.png']
{'0': 0}
[[0.000 0.344 0.380 0.000 0.276]]


In [12]:
val_datagen = tf.keras.preprocessing.image.ImageDataGenerator(rescale=1./255)

val_generator = val_datagen.flow_from_directory(
        '/content/CNNDATA/MyDrive/CNNDATA/Test/005/',
        target_size=(pictureWeightHeightSize, pictureWeightHeightSize),    
        batch_size=numberOfClass,
        class_mode='categorical')
print("-- Predict --")
output = model.predict(val_generator)
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
print(val_generator.filenames)
print(val_generator.class_indices)
print(output)

Found 1 images belonging to 1 classes.
-- Predict --
['0/047edge.png']
{'0': 0}
[[0.000 0.344 0.380 0.000 0.276]]


In [13]:
val_datagen = tf.keras.preprocessing.image.ImageDataGenerator(rescale=1./255)

val_generator = val_datagen.flow_from_directory(
        '/content/CNNDATA/MyDrive/CNNDATA/Test/006/',
        target_size=(pictureWeightHeightSize, pictureWeightHeightSize),    
        batch_size=numberOfClass,
        class_mode='categorical')
print("-- Predict --")
output = model.predict(val_generator)
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
print(val_generator.filenames)
print(val_generator.class_indices)
print(output)

Found 1 images belonging to 1 classes.
-- Predict --
['0/048edge.png']
{'0': 0}
[[0.000 0.344 0.380 0.000 0.276]]


In [14]:
val_datagen = tf.keras.preprocessing.image.ImageDataGenerator(rescale=1./255)

val_generator = val_datagen.flow_from_directory(
        '/content/CNNDATA/MyDrive/CNNDATA/Test/007/',
        target_size=(pictureWeightHeightSize, pictureWeightHeightSize),    
        batch_size=numberOfClass,
        class_mode='categorical')
print("-- Predict --")
output = model.predict(val_generator)
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
print(val_generator.filenames)
print(val_generator.class_indices)
print(output)

Found 1 images belonging to 1 classes.
-- Predict --
['0/063edge.png']
{'0': 0}
[[0.000 0.344 0.380 0.000 0.276]]


In [15]:
val_datagen = tf.keras.preprocessing.image.ImageDataGenerator(rescale=1./255)

val_generator = val_datagen.flow_from_directory(
        '/content/CNNDATA/MyDrive/CNNDATA/Test/008/',
        target_size=(pictureWeightHeightSize, pictureWeightHeightSize),    
        batch_size=numberOfClass,
        class_mode='categorical')
print("-- Predict --")
output = model.predict(val_generator)
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
print(val_generator.filenames)
print(val_generator.class_indices)
print(output)

Found 1 images belonging to 1 classes.
-- Predict --
['0/064edge.png']
{'0': 0}
[[0.000 0.344 0.380 0.000 0.276]]


In [16]:
val_datagen = tf.keras.preprocessing.image.ImageDataGenerator(rescale=1./255)

val_generator = val_datagen.flow_from_directory(
        '/content/CNNDATA/MyDrive/CNNDATA/Test/009/',
        target_size=(pictureWeightHeightSize, pictureWeightHeightSize),    
        batch_size=numberOfClass,
        class_mode='categorical')
print("-- Predict --")
output = model.predict(val_generator)
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
print(val_generator.filenames)
print(val_generator.class_indices)
print(output)

Found 1 images belonging to 1 classes.
-- Predict --
['0/079edge.png']
{'0': 0}
[[0.000 0.344 0.380 0.000 0.276]]


In [25]:
val_datagen = tf.keras.preprocessing.image.ImageDataGenerator(rescale=1./255)

val_generator = val_datagen.flow_from_directory(
        '/content/CNNDATA/MyDrive/CNNDATA/Test/010/',
        target_size=(pictureWeightHeightSize, pictureWeightHeightSize),    
        batch_size=numberOfClass,
        class_mode='categorical')
print("-- Predict --")
output = model.predict(val_generator)
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
print(val_generator.filenames)
print(val_generator.class_indices)
print(output)

Found 1 images belonging to 1 classes.
-- Predict --
['0/080edge.png']
{'0': 0}
[[0.000 0.344 0.380 0.000 0.276]]
