<a href="https://colab.research.google.com/github/NewTAs/EECuC/blob/main/EECuC_220112_Try2G.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import os
import re
import glob
import cv2
import numpy as np
from sklearn.model_selection import train_test_split

import tensorflow as tf

from google.colab import drive
drive.mount('CNNDATA')

Drive already mounted at CNNDATA; to attempt to forcibly remount, call drive.mount("CNNDATA", force_remount=True).


In [5]:
numberOfClass = 5
pictureWeightHeightSize = 224

train_datagen = tf.keras.preprocessing.image.ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow_from_directory(
        '/content/CNNDATA/MyDrive/CNNDATA/Train/',
        target_size=(pictureWeightHeightSize, pictureWeightHeightSize),
        batch_size=numberOfClass,
        class_mode='categorical')

test_datagen = tf.keras.preprocessing.image.ImageDataGenerator(rescale=1./255)

test_generator = test_datagen.flow_from_directory(
        '/content/CNNDATA/MyDrive/CNNDATA/Validation/',
        target_size=(pictureWeightHeightSize, pictureWeightHeightSize),    
        batch_size=numberOfClass,
        class_mode='categorical')

Found 100 images belonging to 5 classes.
Found 40 images belonging to 5 classes.


In [6]:
from tensorflow.keras.applications import NASNetMobile

model = NASNetMobile(include_top=True, weights=None, input_shape=(224, 224, 3), pooling=max, classes=5)

In [7]:
model.compile(loss='categorical_crossentropy', metrics=['accuracy'], optimizer='adam')
model.summary()

Model: "NASNet"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_1 (InputLayer)           [(None, 224, 224, 3  0           []                               
                                )]                                                                
                                                                                                  
 stem_conv1 (Conv2D)            (None, 111, 111, 32  864         ['input_1[0][0]']                
                                )                                                                 
                                                                                                  
 stem_bn1 (BatchNormalization)  (None, 111, 111, 32  128         ['stem_conv1[0][0]']             
                                )                                                            

In [8]:
model.fit(train_generator, epochs=100, validation_data=test_generator)

Epoch 1/100
20/20 [==============================] - 62s 1s/step - loss: 1.9571 - accuracy: 0.2800 - val_loss: 8.7366 - val_accuracy: 0.2000
Epoch 2/100
20/20 [==============================] - 5s 228ms/step - loss: 1.1939 - accuracy: 0.5500 - val_loss: 6.6833 - val_accuracy: 0.2000
Epoch 3/100
20/20 [==============================] - 4s 223ms/step - loss: 1.3184 - accuracy: 0.6100 - val_loss: 11.0437 - val_accuracy: 0.2000
Epoch 4/100
20/20 [==============================] - 4s 220ms/step - loss: 0.8468 - accuracy: 0.7300 - val_loss: 9.9229 - val_accuracy: 0.2000
Epoch 5/100
20/20 [==============================] - 4s 220ms/step - loss: 0.7704 - accuracy: 0.7300 - val_loss: 9.9770 - val_accuracy: 0.2000
Epoch 6/100
20/20 [==============================] - 4s 225ms/step - loss: 0.5826 - accuracy: 0.8000 - val_loss: 10.8773 - val_accuracy: 0.2000
Epoch 7/100
20/20 [==============================] - 4s 224ms/step - loss: 0.3068 - accuracy: 0.9100 - val_loss: 7.9429 - val_accuracy: 0.2000

In [9]:
print("-- Evaluate --")
scores = model.evaluate(test_generator)
print("%s: %.2f%%" %(model.metrics_names[1], scores[1]*100))

-- Evaluate --
8/8 [==============================] - 1s 60ms/step - loss: 5.0227 - accuracy: 0.5500
accuracy: 55.00%


In [10]:
import matplotlib.pyplot as plt

In [11]:
val_datagen = tf.keras.preprocessing.image.ImageDataGenerator(rescale=1./255)

val_generator = val_datagen.flow_from_directory(
        '/content/CNNDATA/MyDrive/CNNDATA/Test/001/',
        target_size=(pictureWeightHeightSize, pictureWeightHeightSize),    
        batch_size=numberOfClass,
        class_mode='categorical')
print("-- Predict --")
output = model.predict(val_generator)
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
print(val_generator.filenames)
print(val_generator.class_indices)
print(output)

Found 1 images belonging to 1 classes.
-- Predict --
['0/015edge.png']
{'0': 0}
[[0.000 0.489 0.213 0.297 0.000]]


In [12]:
val_datagen = tf.keras.preprocessing.image.ImageDataGenerator(rescale=1./255)

val_generator = val_datagen.flow_from_directory(
        '/content/CNNDATA/MyDrive/CNNDATA/Test/002/',
        target_size=(pictureWeightHeightSize, pictureWeightHeightSize),    
        batch_size=numberOfClass,
        class_mode='categorical')
print("-- Predict --")
output = model.predict(val_generator)
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
print(val_generator.filenames)
print(val_generator.class_indices)
print(output)

Found 1 images belonging to 1 classes.
-- Predict --
['0/016edge.png']
{'0': 0}
[[0.000 0.463 0.179 0.358 0.001]]


In [13]:
val_datagen = tf.keras.preprocessing.image.ImageDataGenerator(rescale=1./255)

val_generator = val_datagen.flow_from_directory(
        '/content/CNNDATA/MyDrive/CNNDATA/Test/003/',
        target_size=(pictureWeightHeightSize, pictureWeightHeightSize),    
        batch_size=numberOfClass,
        class_mode='categorical')
print("-- Predict --")
output = model.predict(val_generator)
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
print(val_generator.filenames)
print(val_generator.class_indices)
print(output)

Found 1 images belonging to 1 classes.
-- Predict --
['0/031edge.png']
{'0': 0}
[[0.000 0.390 0.265 0.345 0.000]]


In [14]:
val_datagen = tf.keras.preprocessing.image.ImageDataGenerator(rescale=1./255)

val_generator = val_datagen.flow_from_directory(
        '/content/CNNDATA/MyDrive/CNNDATA/Test/004/',
        target_size=(pictureWeightHeightSize, pictureWeightHeightSize),    
        batch_size=numberOfClass,
        class_mode='categorical')
print("-- Predict --")
output = model.predict(val_generator)
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
print(val_generator.filenames)
print(val_generator.class_indices)
print(output)

Found 1 images belonging to 1 classes.
-- Predict --
['0/032edge.png']
{'0': 0}
[[0.000 0.423 0.213 0.364 0.000]]


In [15]:
val_datagen = tf.keras.preprocessing.image.ImageDataGenerator(rescale=1./255)

val_generator = val_datagen.flow_from_directory(
        '/content/CNNDATA/MyDrive/CNNDATA/Test/005/',
        target_size=(pictureWeightHeightSize, pictureWeightHeightSize),    
        batch_size=numberOfClass,
        class_mode='categorical')
print("-- Predict --")
output = model.predict(val_generator)
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
print(val_generator.filenames)
print(val_generator.class_indices)
print(output)

Found 1 images belonging to 1 classes.
-- Predict --
['0/047edge.png']
{'0': 0}
[[0.000 0.391 0.289 0.320 0.000]]


In [16]:
val_datagen = tf.keras.preprocessing.image.ImageDataGenerator(rescale=1./255)

val_generator = val_datagen.flow_from_directory(
        '/content/CNNDATA/MyDrive/CNNDATA/Test/006/',
        target_size=(pictureWeightHeightSize, pictureWeightHeightSize),    
        batch_size=numberOfClass,
        class_mode='categorical')
print("-- Predict --")
output = model.predict(val_generator)
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
print(val_generator.filenames)
print(val_generator.class_indices)
print(output)

Found 1 images belonging to 1 classes.
-- Predict --
['0/048edge.png']
{'0': 0}
[[0.000 0.362 0.345 0.292 0.000]]


In [17]:
val_datagen = tf.keras.preprocessing.image.ImageDataGenerator(rescale=1./255)

val_generator = val_datagen.flow_from_directory(
        '/content/CNNDATA/MyDrive/CNNDATA/Test/007/',
        target_size=(pictureWeightHeightSize, pictureWeightHeightSize),    
        batch_size=numberOfClass,
        class_mode='categorical')
print("-- Predict --")
output = model.predict(val_generator)
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
print(val_generator.filenames)
print(val_generator.class_indices)
print(output)

Found 1 images belonging to 1 classes.
-- Predict --
['0/063edge.png']
{'0': 0}
[[0.000 0.320 0.038 0.641 0.001]]


In [18]:
val_datagen = tf.keras.preprocessing.image.ImageDataGenerator(rescale=1./255)

val_generator = val_datagen.flow_from_directory(
        '/content/CNNDATA/MyDrive/CNNDATA/Test/008/',
        target_size=(pictureWeightHeightSize, pictureWeightHeightSize),    
        batch_size=numberOfClass,
        class_mode='categorical')
print("-- Predict --")
output = model.predict(val_generator)
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
print(val_generator.filenames)
print(val_generator.class_indices)
print(output)

Found 1 images belonging to 1 classes.
-- Predict --
['0/064edge.png']
{'0': 0}
[[0.000 0.443 0.245 0.312 0.000]]


In [19]:
val_datagen = tf.keras.preprocessing.image.ImageDataGenerator(rescale=1./255)

val_generator = val_datagen.flow_from_directory(
        '/content/CNNDATA/MyDrive/CNNDATA/Test/009/',
        target_size=(pictureWeightHeightSize, pictureWeightHeightSize),    
        batch_size=numberOfClass,
        class_mode='categorical')
print("-- Predict --")
output = model.predict(val_generator)
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
print(val_generator.filenames)
print(val_generator.class_indices)
print(output)

Found 1 images belonging to 1 classes.
-- Predict --
['0/079edge.png']
{'0': 0}
[[0.000 0.375 0.343 0.281 0.000]]


In [20]:
val_datagen = tf.keras.preprocessing.image.ImageDataGenerator(rescale=1./255)

val_generator = val_datagen.flow_from_directory(
        '/content/CNNDATA/MyDrive/CNNDATA/Test/010/',
        target_size=(pictureWeightHeightSize, pictureWeightHeightSize),    
        batch_size=numberOfClass,
        class_mode='categorical')
print("-- Predict --")
output = model.predict(val_generator)
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
print(val_generator.filenames)
print(val_generator.class_indices)
print(output)

Found 1 images belonging to 1 classes.
-- Predict --
['0/080edge.png']
{'0': 0}
[[0.000 0.486 0.170 0.343 0.000]]
