<a href="https://colab.research.google.com/github/NewTAs/EECuC/blob/main/EECuC_220112_Try2C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import os
import re
import glob
import cv2
import numpy as np
from sklearn.model_selection import train_test_split

import tensorflow as tf

from google.colab import drive
drive.mount('CNNDATA')

Mounted at CNNDATA


In [ ]:
numberOfClass = 4
pictureWeightHeightSize = 224

train_datagen = tf.keras.preprocessing.image.ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow_from_directory(
        '/content/CNNDATA/MyDrive/CNNDATA/Train/',
        target_size=(pictureWeightHeightSize, pictureWeightHeightSize),
        batch_size=numberOfClass,
        class_mode='categorical')

test_datagen = tf.keras.preprocessing.image.ImageDataGenerator(rescale=1./255)

test_generator = test_datagen.flow_from_directory(
        '/content/CNNDATA/MyDrive/CNNDATA/Validation/',
        target_size=(pictureWeightHeightSize, pictureWeightHeightSize),    
        batch_size=numberOfClass,
        class_mode='categorical')

Found 96 images belonging to 4 classes.
Found 24 images belonging to 4 classes.


In [ ]:
from tensorflow.keras.applications import ResNet50V2

model = ResNet50V2(include_top=True, weights=None, input_shape=(224, 224, 3), pooling=max, classes=4)

In [ ]:
model.compile(loss='categorical_crossentropy', metrics=['accuracy'], optimizer='adam')
model.summary()

Model: "resnet50v2"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_1 (InputLayer)           [(None, 224, 224, 3  0           []                               
                                )]                                                                
                                                                                                  
 conv1_pad (ZeroPadding2D)      (None, 230, 230, 3)  0           ['input_1[0][0]']                
                                                                                                  
 conv1_conv (Conv2D)            (None, 112, 112, 64  9472        ['conv1_pad[0][0]']              
                                )                                                                 
                                                                                         

In [ ]:
model.fit(train_generator, epochs=100, validation_data=test_generator)

Epoch 1/100
24/24 [==============================] - 36s 791ms/step - loss: 1.5272 - accuracy: 0.4271 - val_loss: 5.9200 - val_accuracy: 0.2500
Epoch 2/100
24/24 [==============================] - 4s 158ms/step - loss: 0.7097 - accuracy: 0.7292 - val_loss: 6.9607 - val_accuracy: 0.2500
Epoch 3/100
24/24 [==============================] - 4s 155ms/step - loss: 0.4139 - accuracy: 0.8125 - val_loss: 9.4828 - val_accuracy: 0.2500
Epoch 4/100
24/24 [==============================] - 4s 156ms/step - loss: 0.5143 - accuracy: 0.7708 - val_loss: 7.5899 - val_accuracy: 0.2500
Epoch 5/100
24/24 [==============================] - 4s 156ms/step - loss: 0.3660 - accuracy: 0.8438 - val_loss: 14.8675 - val_accuracy: 0.2500
Epoch 6/100
24/24 [==============================] - 4s 157ms/step - loss: 0.1942 - accuracy: 0.9583 - val_loss: 17.3760 - val_accuracy: 0.2500
Epoch 7/100
24/24 [==============================] - 4s 156ms/step - loss: 0.4136 - accuracy: 0.8542 - val_loss: 5.2465 - val_accuracy: 0.2

In [ ]:
print("-- Evaluate --")
scores = model.evaluate(test_generator)
print("%s: %.2f%%" %(model.metrics_names[1], scores[1]*100))

-- Evaluate --
6/6 [==============================] - 0s 44ms/step - loss: 1.1690 - accuracy: 0.7500
accuracy: 75.00%


In [ ]:
import matplotlib.pyplot as plt

In [ ]:
val_datagen = tf.keras.preprocessing.image.ImageDataGenerator(rescale=1./255)

val_generator = val_datagen.flow_from_directory(
        '/content/CNNDATA/MyDrive/CNNDATA/Test/001/',
        target_size=(pictureWeightHeightSize, pictureWeightHeightSize),    
        batch_size=numberOfClass,
        class_mode='categorical')
print("-- Predict --")
output = model.predict(val_generator)
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
print(val_generator.filenames)
print(val_generator.class_indices)
print(output)

Found 1 images belonging to 1 classes.
-- Predict --
['0/016rsedge.png']
{'0': 0}
[[0.983 0.017 0.000 0.000]]


In [ ]:
val_datagen = tf.keras.preprocessing.image.ImageDataGenerator(rescale=1./255)

val_generator = val_datagen.flow_from_directory(
        '/content/CNNDATA/MyDrive/CNNDATA/Test/002/',
        target_size=(pictureWeightHeightSize, pictureWeightHeightSize),    
        batch_size=numberOfClass,
        class_mode='categorical')
print("-- Predict --")
output = model.predict(val_generator)
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
print(val_generator.filenames)
print(val_generator.class_indices)
print(output)

Found 1 images belonging to 1 classes.
-- Predict --
['0/017rsedge.png']
{'0': 0}
[[1.000 0.000 0.000 0.000]]


In [ ]:
val_datagen = tf.keras.preprocessing.image.ImageDataGenerator(rescale=1./255)

val_generator = val_datagen.flow_from_directory(
        '/content/CNNDATA/MyDrive/CNNDATA/Test/003/',
        target_size=(pictureWeightHeightSize, pictureWeightHeightSize),    
        batch_size=numberOfClass,
        class_mode='categorical')
print("-- Predict --")
output = model.predict(val_generator)
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
print(val_generator.filenames)
print(val_generator.class_indices)
print(output)

Found 1 images belonging to 1 classes.
-- Predict --
['0/033rsedge.png']
{'0': 0}
[[0.016 0.984 0.000 0.000]]


In [ ]:
val_datagen = tf.keras.preprocessing.image.ImageDataGenerator(rescale=1./255)

val_generator = val_datagen.flow_from_directory(
        '/content/CNNDATA/MyDrive/CNNDATA/Test/004/',
        target_size=(pictureWeightHeightSize, pictureWeightHeightSize),    
        batch_size=numberOfClass,
        class_mode='categorical')
print("-- Predict --")
output = model.predict(val_generator)
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
print(val_generator.filenames)
print(val_generator.class_indices)
print(output)

Found 1 images belonging to 1 classes.
-- Predict --
['0/034rsedge.png']
{'0': 0}
[[0.008 0.992 0.000 0.000]]


In [ ]:
val_datagen = tf.keras.preprocessing.image.ImageDataGenerator(rescale=1./255)

val_generator = val_datagen.flow_from_directory(
        '/content/CNNDATA/MyDrive/CNNDATA/Test/005/',
        target_size=(pictureWeightHeightSize, pictureWeightHeightSize),    
        batch_size=numberOfClass,
        class_mode='categorical')
print("-- Predict --")
output = model.predict(val_generator)
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
print(val_generator.filenames)
print(val_generator.class_indices)
print(output)

Found 1 images belonging to 1 classes.
-- Predict --
['0/050rsedge.png']
{'0': 0}
[[0.002 0.000 0.998 0.000]]


In [ ]:
val_datagen = tf.keras.preprocessing.image.ImageDataGenerator(rescale=1./255)

val_generator = val_datagen.flow_from_directory(
        '/content/CNNDATA/MyDrive/CNNDATA/Test/006/',
        target_size=(pictureWeightHeightSize, pictureWeightHeightSize),    
        batch_size=numberOfClass,
        class_mode='categorical')
print("-- Predict --")
output = model.predict(val_generator)
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
print(val_generator.filenames)
print(val_generator.class_indices)
print(output)

Found 1 images belonging to 1 classes.
-- Predict --
['0/051rsedge.png']
{'0': 0}
[[0.903 0.000 0.097 0.000]]


In [ ]:
val_datagen = tf.keras.preprocessing.image.ImageDataGenerator(rescale=1./255)

val_generator = val_datagen.flow_from_directory(
        '/content/CNNDATA/MyDrive/CNNDATA/Test/007/',
        target_size=(pictureWeightHeightSize, pictureWeightHeightSize),    
        batch_size=numberOfClass,
        class_mode='categorical')
print("-- Predict --")
output = model.predict(val_generator)
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
print(val_generator.filenames)
print(val_generator.class_indices)
print(output)

Found 1 images belonging to 1 classes.
-- Predict --
['0/067rsedge.png']
{'0': 0}
[[0.053 0.177 0.000 0.770]]


In [ ]:
val_datagen = tf.keras.preprocessing.image.ImageDataGenerator(rescale=1./255)

val_generator = val_datagen.flow_from_directory(
        '/content/CNNDATA/MyDrive/CNNDATA/Test/008/',
        target_size=(pictureWeightHeightSize, pictureWeightHeightSize),    
        batch_size=numberOfClass,
        class_mode='categorical')
print("-- Predict --")
output = model.predict(val_generator)
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
print(val_generator.filenames)
print(val_generator.class_indices)
print(output)

Found 1 images belonging to 1 classes.
-- Predict --
['0/068rsedge.png']
{'0': 0}
[[0.000 0.000 0.000 1.000]]
