<a href="https://colab.research.google.com/github/NewTAs/EECuC/blob/main/EECuC_220110_Try1D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import os
import re
import glob
import cv2
import numpy as np
from sklearn.model_selection import train_test_split

import tensorflow as tf

from google.colab import drive
drive.mount('CNNDATA')

Drive already mounted at CNNDATA; to attempt to forcibly remount, call drive.mount("CNNDATA", force_remount=True).


In [2]:
numberOfClass = 5
pictureWeightHeightSize = 224

train_datagen = tf.keras.preprocessing.image.ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow_from_directory(
        '/content/CNNDATA/MyDrive/CNNDATA/Train/',
        target_size=(pictureWeightHeightSize, pictureWeightHeightSize),
        batch_size=numberOfClass,
        class_mode='categorical')

test_datagen = tf.keras.preprocessing.image.ImageDataGenerator(rescale=1./255)

test_generator = test_datagen.flow_from_directory(
        '/content/CNNDATA/MyDrive/CNNDATA/Validation/',
        target_size=(pictureWeightHeightSize, pictureWeightHeightSize),    
        batch_size=numberOfClass,
        class_mode='categorical')

Found 300 images belonging to 5 classes.
Found 120 images belonging to 5 classes.


In [3]:
from tensorflow.keras.applications import ResNet50V2

model = ResNet50V2(include_top=True, weights=None, input_shape=(224, 224, 3), pooling=max, classes=5)

In [4]:
model.compile(loss='categorical_crossentropy', metrics=['accuracy'], optimizer='adam')
model.summary()

Model: "resnet50v2"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_1 (InputLayer)           [(None, 224, 224, 3  0           []                               
                                )]                                                                
                                                                                                  
 conv1_pad (ZeroPadding2D)      (None, 230, 230, 3)  0           ['input_1[0][0]']                
                                                                                                  
 conv1_conv (Conv2D)            (None, 112, 112, 64  9472        ['conv1_pad[0][0]']              
                                )                                                                 
                                                                                         

In [5]:
model.fit(train_generator, epochs=100, validation_data=test_generator)

Epoch 1/100
60/60 [==============================] - 42s 547ms/step - loss: 1.8645 - accuracy: 0.3733 - val_loss: 6.9167 - val_accuracy: 0.2000
Epoch 2/100
60/60 [==============================] - 15s 255ms/step - loss: 1.4040 - accuracy: 0.4267 - val_loss: 22.7430 - val_accuracy: 0.2000
Epoch 3/100
60/60 [==============================] - 15s 256ms/step - loss: 1.2063 - accuracy: 0.5667 - val_loss: 35.2342 - val_accuracy: 0.3000
Epoch 4/100
60/60 [==============================] - 15s 255ms/step - loss: 1.0254 - accuracy: 0.6233 - val_loss: 10.2550 - val_accuracy: 0.2500
Epoch 5/100
60/60 [==============================] - 15s 257ms/step - loss: 0.9991 - accuracy: 0.6400 - val_loss: 4.8005 - val_accuracy: 0.1917
Epoch 6/100
60/60 [==============================] - 15s 255ms/step - loss: 0.8362 - accuracy: 0.6733 - val_loss: 6.8296 - val_accuracy: 0.2500
Epoch 7/100
60/60 [==============================] - 15s 255ms/step - loss: 0.6889 - accuracy: 0.7533 - val_loss: 10.6472 - val_accur

In [6]:
print("-- Evaluate --")
scores = model.evaluate(test_generator)
print("%s: %.2f%%" %(model.metrics_names[1], scores[1]*100))

-- Evaluate --
24/24 [==============================] - 2s 74ms/step - loss: 15.8259 - accuracy: 0.4583
accuracy: 45.83%


In [7]:
import matplotlib.pyplot as plt

In [8]:
val_datagen = tf.keras.preprocessing.image.ImageDataGenerator(rescale=1./255)

val_generator = val_datagen.flow_from_directory(
        '/content/CNNDATA/MyDrive/CNNDATA/Test/001/',
        target_size=(pictureWeightHeightSize, pictureWeightHeightSize),    
        batch_size=numberOfClass,
        class_mode='categorical')
print("-- Predict --")
output = model.predict(val_generator)
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
print(val_generator.filenames)
print(val_generator.class_indices)
print(output)

Found 1 images belonging to 1 classes.
-- Predict --
['0/015sub.png']
{'0': 0}
[[0.000 0.000 1.000 0.000 0.000]]


In [9]:
val_datagen = tf.keras.preprocessing.image.ImageDataGenerator(rescale=1./255)

val_generator = val_datagen.flow_from_directory(
        '/content/CNNDATA/MyDrive/CNNDATA/Test/002/',
        target_size=(pictureWeightHeightSize, pictureWeightHeightSize),    
        batch_size=numberOfClass,
        class_mode='categorical')
print("-- Predict --")
output = model.predict(val_generator)
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
print(val_generator.filenames)
print(val_generator.class_indices)
print(output)

Found 1 images belonging to 1 classes.
-- Predict --
['0/016sub.png']
{'0': 0}
[[0.084 0.573 0.343 0.000 0.000]]


In [10]:
val_datagen = tf.keras.preprocessing.image.ImageDataGenerator(rescale=1./255)

val_generator = val_datagen.flow_from_directory(
        '/content/CNNDATA/MyDrive/CNNDATA/Test/003/',
        target_size=(pictureWeightHeightSize, pictureWeightHeightSize),    
        batch_size=numberOfClass,
        class_mode='categorical')
print("-- Predict --")
output = model.predict(val_generator)
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
print(val_generator.filenames)
print(val_generator.class_indices)
print(output)

Found 1 images belonging to 1 classes.
-- Predict --
['0/031sub.png']
{'0': 0}
[[0.999 0.001 0.000 0.000 0.000]]


In [11]:
val_datagen = tf.keras.preprocessing.image.ImageDataGenerator(rescale=1./255)

val_generator = val_datagen.flow_from_directory(
        '/content/CNNDATA/MyDrive/CNNDATA/Test/004/',
        target_size=(pictureWeightHeightSize, pictureWeightHeightSize),    
        batch_size=numberOfClass,
        class_mode='categorical')
print("-- Predict --")
output = model.predict(val_generator)
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
print(val_generator.filenames)
print(val_generator.class_indices)
print(output)

Found 1 images belonging to 1 classes.
-- Predict --
['0/032sub.png']
{'0': 0}
[[0.935 0.061 0.004 0.000 0.000]]


In [12]:
val_datagen = tf.keras.preprocessing.image.ImageDataGenerator(rescale=1./255)

val_generator = val_datagen.flow_from_directory(
        '/content/CNNDATA/MyDrive/CNNDATA/Test/005/',
        target_size=(pictureWeightHeightSize, pictureWeightHeightSize),    
        batch_size=numberOfClass,
        class_mode='categorical')
print("-- Predict --")
output = model.predict(val_generator)
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
print(val_generator.filenames)
print(val_generator.class_indices)
print(output)

Found 1 images belonging to 1 classes.
-- Predict --
['0/047sub.png']
{'0': 0}
[[0.982 0.017 0.001 0.000 0.000]]


In [13]:
val_datagen = tf.keras.preprocessing.image.ImageDataGenerator(rescale=1./255)

val_generator = val_datagen.flow_from_directory(
        '/content/CNNDATA/MyDrive/CNNDATA/Test/006/',
        target_size=(pictureWeightHeightSize, pictureWeightHeightSize),    
        batch_size=numberOfClass,
        class_mode='categorical')
print("-- Predict --")
output = model.predict(val_generator)
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
print(val_generator.filenames)
print(val_generator.class_indices)
print(output)

Found 1 images belonging to 1 classes.
-- Predict --
['0/048sub.png']
{'0': 0}
[[0.000 0.022 0.978 0.000 0.000]]


In [14]:
val_datagen = tf.keras.preprocessing.image.ImageDataGenerator(rescale=1./255)

val_generator = val_datagen.flow_from_directory(
        '/content/CNNDATA/MyDrive/CNNDATA/Test/007/',
        target_size=(pictureWeightHeightSize, pictureWeightHeightSize),    
        batch_size=numberOfClass,
        class_mode='categorical')
print("-- Predict --")
output = model.predict(val_generator)
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
print(val_generator.filenames)
print(val_generator.class_indices)
print(output)

Found 1 images belonging to 1 classes.
-- Predict --
['0/063sub.png']
{'0': 0}
[[0.000 0.083 0.917 0.000 0.000]]


In [15]:
val_datagen = tf.keras.preprocessing.image.ImageDataGenerator(rescale=1./255)

val_generator = val_datagen.flow_from_directory(
        '/content/CNNDATA/MyDrive/CNNDATA/Test/008/',
        target_size=(pictureWeightHeightSize, pictureWeightHeightSize),    
        batch_size=numberOfClass,
        class_mode='categorical')
print("-- Predict --")
output = model.predict(val_generator)
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
print(val_generator.filenames)
print(val_generator.class_indices)
print(output)

Found 1 images belonging to 1 classes.
-- Predict --
['0/064sub.png']
{'0': 0}
[[0.000 0.000 1.000 0.000 0.000]]


In [16]:
val_datagen = tf.keras.preprocessing.image.ImageDataGenerator(rescale=1./255)

val_generator = val_datagen.flow_from_directory(
        '/content/CNNDATA/MyDrive/CNNDATA/Test/009/',
        target_size=(pictureWeightHeightSize, pictureWeightHeightSize),    
        batch_size=numberOfClass,
        class_mode='categorical')
print("-- Predict --")
output = model.predict(val_generator)
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
print(val_generator.filenames)
print(val_generator.class_indices)
print(output)

Found 1 images belonging to 1 classes.
-- Predict --
['0/079sub.png']
{'0': 0}
[[1.000 0.000 0.000 0.000 0.000]]


In [17]:
val_datagen = tf.keras.preprocessing.image.ImageDataGenerator(rescale=1./255)

val_generator = val_datagen.flow_from_directory(
        '/content/CNNDATA/MyDrive/CNNDATA/Test/010/',
        target_size=(pictureWeightHeightSize, pictureWeightHeightSize),    
        batch_size=numberOfClass,
        class_mode='categorical')
print("-- Predict --")
output = model.predict(val_generator)
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
print(val_generator.filenames)
print(val_generator.class_indices)
print(output)

Found 1 images belonging to 1 classes.
-- Predict --
['0/080sub.png']
{'0': 0}
[[0.000 0.001 0.999 0.000 0.000]]
